package:
  name: magpy
  version: 1.0

source:
  git_url: https://github.com/owlas/magpy
  git_rev: dom

build:
  number: 0

requirements:
  build:
    - setuptools
    - openblas
    - cython
    - numpy >=1.11
  run:
    - setuptools
    - openblas
    - numpy >=1.11
    - matplotlib
    - toolz
    - joblib
    - scipy
    - transforms3d

about:
  home: https://github.com/owlas/magpy
  license: BSD-3-Clause

test:
  imports:
    - magpy
  requires:
    - pytest
  source_files:
    - test/tests
    - test/test_magpy.py
    - test/test_geometries.py
  commands:
    - LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH test/tests
    - pytest -v test/test_magpy.py test/test_geometries.py
