package:
  name: magpy
  version: "0.1.dev1"

  git_url: https://github.com/owlas/magpy
  git_rev: "0.1.dev1"

build:
  number: 0

requirements:
  build:
    - setuptools
    - openblas
    - cython
    - numpy >=1.11
  run:
    - setuptools
    - openblas
    - numpy >=1.11
    - matplotlib
    - toolz
    - joblib
    - scipy

about:
  home: https://github.com/owlas/magpy
  license: BSD-3-Clause

test:
  imports:
    - magpy
  requires:
    - pytest
  source_files:
    - test/tests
    - test/test_magpy.py
  commands:
    - test/tests
    - pytest -v test/test_magpy.py
