channels:
  - conda-forge

dependencies:
  - python==3.5
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - nbsphinx
    - breathe
    - sphinx-rtd-theme
    - git+https://github.com/owlas/JuliaDoc.git
